name: Deploy master branch

on:
  push:
    branches:
      - master
  workflow_dispatch:
  
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Checkout@v2
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build & Unit Test  
        run: npm ci && npm run build && npm run test:unit
      - name: Setup serverless
        run: npm i -g serverless
      - name: Serverless deploy
        run: npm run build && npm i -g serverless && npm run deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Run Api Test
        run: npm run test:api    